### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by HenryTraill** [tutorcruncher/Chronos#13]
* [ ] Change delete endpoint to signed dict
* [ ] Change get logs to signed dict
* [ ] Add logfire
* [ ] Add sentry reporting
* [ ] Fix naming conventions
* [ ] Fix doc strings
* [ ] Get explicit with comments
* [ ] Complete test coverage

**Comment by PrenSJ2** [comment]
`/send-webhook-callback/{url_extension}`

not allowing any url extension

**Comment by Pager07** [comment]
when TC was sending webhook, the receiver of the webhook, received json object
![image](https://github.com/user-attachments/assets/0d893ee8-c931-4d01-9466-9f8d1205617d)

when chronos sends the webhook, the receiver of the webhook, received string json
![image](https://github.com/user-attachments/assets/c15f3aa2-6ea5-400d-85f7-c8c596cfe9b8)
